### ISSUE TITLE
<ul> i.pv. div

### ISSUE THREAD

**Issue by tom-2810** [Akikosophia/your-tribe-profile-card#2]
Aangezien het een lijst is van gegevens zou je deze in een lijst kunnen plaatsen. <ul> met daarin list items <li> in plaats van losse <p> elementen. Want het zijn geen paragraphs.

https://github.com/Akikosophia/your-tribe-profile-card/blob/29ffedae6e0dcf78127ee05c486a557fb6f5aec0/index.html#L19-L23

**Comment by Akikosophia** [comment]
Gefikst!
